# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Zahra
tagline:          'Home'
description:      'Sworn & State-Certified'
url:              https://zahra-claire-bahrani-peacock.github.io/
baseurl:          /

author:
  name:           'Zahra-Claire Bahrani-Peacock'
  url:            https://www.linkedin.com/in/zahra-claire-bahrani-peacock

paginate:         5

# Custom vars
version:          2.1.0
sidebar_home_button: false

github:
  repo:           https://github.com/Zahra-Claire-Bahrani-Peacock/
