# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Zahra
tagline:          'Peacock translations'
description:      'Sworn & State-Certified  
Translator  
Interpreter  
Proofreader'
url:              https://peacock-translations.github.io/
baseurl:          /

author:
  name:           'Zahra-Claire Bahrani-Peacock'
  url:            https://www.linkedin.com/in/zahra-claire-bahrani-peacock

paginate:         5

# Custom vars
version:          2.1.0

sidebar_home_link: false

github:
  repo:           https://github.com/peacock-translations/
